/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.syddraf.dim.gui;

import com.syddraf.dim.PreferenceManager;

/**
 *
 * @author syddraf
 */
public class NotificationWindow extends javax.swing.JFrame {

    /**
     * Creates new form NotificationWindow
     */
    public NotificationWindow() {
        initComponents();
        boolean newSound = Boolean.parseBoolean(PreferenceManager.getInstance().get("newMessageSound", "true"));
        boolean newVisual = Boolean.parseBoolean(PreferenceManager.getInstance().get("newMessageVisual", "true"));
        boolean statusSoundB = Boolean.parseBoolean(PreferenceManager.getInstance().get("statusSound", "true"));
        boolean statusVisualB = Boolean.parseBoolean(PreferenceManager.getInstance().get("statusVisual", "true"));
        this.newMessageSound.setSelected(newSound);
        this.newMessageVisual.setSelected(newVisual);
        this.statusSound.setSelected(statusSoundB);
        this.statusVisual.setSelected(statusVisualB);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newMessageSound = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        newMessageVisual = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        statusSound = new javax.swing.JCheckBox();
        statusVisual = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DIM Notifications");

        newMessageSound.setText("Play Sound");
        newMessageSound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newMessageSoundActionPerformed(evt);
            }
        });

        jLabel1.setText("New Message");

        newMessageVisual.setText("Flash Buddy List");
        newMessageVisual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newMessageVisualActionPerformed(evt);
            }
        });

        jLabel2.setText("Status Change");

        statusSound.setText("Play Sound");
        statusSound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusSoundActionPerformed(evt);
            }
        });

        statusVisual.setText("Flash Buddy List");
        statusVisual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusVisualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(statusSound)
                            .addComponent(newMessageVisual)
                            .addComponent(newMessageSound)
                            .addComponent(statusVisual))))
                .addContainerGap(230, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newMessageSound)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newMessageVisual)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusSound)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusVisual)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newMessageSoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newMessageSoundActionPerformed
        PreferenceManager.getInstance().put("newMessageSound", Boolean.toString(this.newMessageSound.isSelected()));
    }//GEN-LAST:event_newMessageSoundActionPerformed

    private void newMessageVisualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newMessageVisualActionPerformed
        PreferenceManager.getInstance().put("newMessageVisual", Boolean.toString(this.newMessageVisual.isSelected()));
    }//GEN-LAST:event_newMessageVisualActionPerformed

    private void statusSoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusSoundActionPerformed
        PreferenceManager.getInstance().put("statusSound", Boolean.toString(this.statusSound.isSelected()));
    }//GEN-LAST:event_statusSoundActionPerformed

    private void statusVisualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusVisualActionPerformed
        PreferenceManager.getInstance().put("statusVisual", Boolean.toString(this.statusVisual.isSelected()));
    }//GEN-LAST:event_statusVisualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NotificationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NotificationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NotificationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NotificationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new NotificationWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JCheckBox newMessageSound;
    private javax.swing.JCheckBox newMessageVisual;
    private javax.swing.JCheckBox statusSound;
    private javax.swing.JCheckBox statusVisual;
    // End of variables declaration//GEN-END:variables
}
